### ISSUE TITLE
Possible bug in break_up_space

### ISSUE THREAD

**Issue by geniass** [mushishi78/box_packer#9]
Correct me if I'm wrong, but in the `break_up_space` method, shouldn't matching dimensions be added and subtracted?

For example: https://github.com/mushishi78/box_packer/blob/d840a56955f9e252860dc064f90d86592c3d9573/box_packer.rb#L92-L94

Shouldn't this rather be
```ruby
 space[:dimensions][0] - placement[:dimensions][0], 
 space[:dimensions][1], 
 space[:dimensions][2]
```

I created a pull request, but it has an additional change that may not be desired behaviour.

**Comment by mushishi78** [comment]
You've got a point. I really should have written some better tests before I did a rewrite. The original used overloads to do vector math and this confused me when copying it over. Would probably be preferable to have a separate PR for the bugfix if possible. Thanks a lot.
